config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#splash'

  get 'ui(/:action)', controller: 'ui' unless Rails.env.production?

  ### Categories ###
  get '/home', to: 'categories#index'
  get '/genre/:id', to: 'categories#show', as: "category"

  ### Videos > Reviews ###
  resources :videos, only: [:show] do 
    collection do 
      post :search, to: "videos#search"
      get :advanced_search, to: "videos#advanced_search", as: :advanced_search
    end

    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  ### Queue ###
  get '/my_queue', to: 'queue_items#index'
  patch '/update_queue', to: 'queue_items#update_queue'
  resources :queue_items, only: [:create, :destroy]

  ### Sessions ###
  get '/login', to: 'sessions#new'
  post '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:create]

  ### Users ###
  get '/register', to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  resources :users, only: [:create, :show]

  ### Followers/Leaders ###
  get '/people', to: 'relationships#index'
  resources :relationships, only: [:destroy, :create]

  ### Forgot Password Workflow ###
  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :forgot_passwords, only: [:create]

  ### Password Reset Workflow ###
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  ### Invitations Workflow ###
  resources :invitations, only: [:new, :create]

  mount StripeEvent::Engine => '/stripe_events'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Tokenable

  has_many :payments
  has_many :reviews, -> {order "created_at DESC"}
  has_many :queue_items, -> { order "position ASC"}
  has_many :leading_relationships, class_name: "Relationship", foreign_key: :leader_id
  has_many :following_relationships, class_name: "Relationship", foreign_key: :follower_id

  validates_presence_of :email, :password, :username
  validates_uniqueness_of :email

  has_secure_password validations: false

  def normalize_queue_item_positions
    queue_items.each_with_index do |queue_item, idx|
      queue_item.update_attributes(position: idx + 1)
    end
  end

  def in_queue?(video)
    queue_items.map(&:video).include?(video)
  end

  def follow(leader)
    Relationship.create(leader_id: leader.id, follower_id: id) unless self == leader
  end

  def follows?(leader)
    Relationship.where(leader_id: leader.id, follower_id: id).exists?
  end

  def deactivate!
    update_column(:active, false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, only: [:show]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    result = UserRegistration.new(@user).register(params[:stripeToken], params[:invitation])

    if result.successful?
      flash[:notice] = "Thank you for registering with MyFlix. Please sign in now."
      redirect_to login_path
    else
      flash[:errors] = result.error_message
      render :new
    end
  end

  def new_with_invitation_token
    invitation = Invitation.find_by(token: params[:token])
    if invitation
      @invitation = invitation
      @user = User.new(email: invitation.recipient_email)
      render :new
    else
      redirect_to expired_token_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/views/users/new.html.haml
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">Stripe.setPublishableKey("#{ENV['STRIPE_PUBLISHABLE_KEY']}")</script>

= javascript_include_tag 'payments'
  
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for @user, html: {class: "form-horizontal", id: "payment-form"} do |f|
        %header
          %h1 Register
        %fieldset
          = f.email_field :email, label: "Email Address"
          = f.password_field :password
          = f.text_field :username, label: "Full Name"
          = hidden_field :invitation, :token
        %fieldset.credit_card
          %span.payment-errors
          .row
            .form-group
              %label.control-label.col-sm-2(for="credit-card-number") Credit Card Number
              .col-sm-6
                %input.form-control(id="credit-card-number" type="text" data-stripe="number")
          .form-group
            %label.control-label.col-sm-2(for="security-code") Security Code
            .col-sm-6
              %input.form-control(id="security-code" type="text" data-stripe="cvc")
          .form-group
            %label.control-label.col-sm-2 Expiration
            .col-sm-3
              = select_month(Date.today, {add_month_numbers: true},  class: 'form-control', data:{stripe: "exp-month"})
            .col-sm-2
              = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, class: 'form-control', data: {stripe: "exp-year"})
        %fieldset.actions.control-group.col-sm-offset-2
          .controls
            %input(class="submit" type="submit" value="Sign Up" class="btn btn-default")
                

app/views/users/show.html.haml
%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email.downcase)}?s=40")
          %h2 
            ="#{@user.username}'s video collections (#{@user.queue_items.count})"
          = link_to "Follow", relationships_path(leader_id: @user.id), method: 'post', class: "btn btn-default" unless current_user == @user || current_user.follows?(@user)
        %table.table
          %thead
            %tr
              %th(width="30%") Video Title
              %th(width="15%") Genre
          %tbody
            - @user.queue_items.map(&:video).each do |video|
              %tr
                %td
                  = link_to video.title, video_path(video)
                %td
                  = link_to video.category.tag, category_path(video.category)

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 #{@user.username}'s Reviews (#{@user.reviews.count})
      %ul
        - @user.reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p
                  = link_to review.video.title
                %col Rating: #{review.rating} / 5
              .col-sm-8
                %p 
                  = review.description