config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#splash'

  get 'ui(/:action)', controller: 'ui' unless Rails.env.production?

  ### Categories ###
  get '/home', to: 'categories#index'
  get '/genre/:id', to: 'categories#show', as: "category"

  ### Videos > Reviews ###
  resources :videos, only: [:show] do 
    collection do 
      post :search, to: "videos#search"
      get :advanced_search, to: "videos#advanced_search", as: :advanced_search
    end

    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  ### Queue ###
  get '/my_queue', to: 'queue_items#index'
  patch '/update_queue', to: 'queue_items#update_queue'
  resources :queue_items, only: [:create, :destroy]

  ### Sessions ###
  get '/login', to: 'sessions#new'
  post '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:create]

  ### Users ###
  get '/register', to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  resources :users, only: [:create, :show]

  ### Followers/Leaders ###
  get '/people', to: 'relationships#index'
  resources :relationships, only: [:destroy, :create]

  ### Forgot Password Workflow ###
  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :forgot_passwords, only: [:create]

  ### Password Reset Workflow ###
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  ### Invitations Workflow ###
  resources :invitations, only: [:new, :create]

  mount StripeEvent::Engine => '/stripe_events'
end

app/models/video.rb
class Video < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks # auto imports to active record to keep them synchronized

  index_name ["myflix", Rails.env].join('_') # create separate indexes for each environment

  belongs_to :category
  has_many :reviews, -> { order 'created_at DESC'}
  has_many :queue_items

  mount_uploader :large_cover, LargeCoverUploader
  mount_uploader :small_cover, SmallCoverUploader

  validates_presence_of :title, :description

  def self.search_by_title(search_term)
    return [] if search_term.blank?
    Video.where("title LIKE ?", "%#{search_term}%").order("created_at DESC")
  end

  def self.search(query, options={})
    search_definition = {
      query: {
        multi_match: {
          query: query,
          fields: ["title^100", "description^50"],
          operator: "and"
        }
      }
    }

    if query.present? && options[:reviews].present?
      search_definition[:query][:multi_match][:fields] << "reviews.description"
    end

    if options[:rating_from].present? || options[:rating_to].present?
      lower_bound = options[:rating_from] ? options[:rating_from].to_f : 0
      upper_bound = options[:rating_to] ? options[:rating_to].to_f : 5

      search_definition[:filter] = {
        range: {
          average_rating: {
            gte: lower_bound,
            lte: upper_bound
          }
        }
      }
    end

    __elasticsearch__.search(search_definition)
  end

  def as_indexed_json(options={})
    as_json(
      only: [:title, :description], 
      methods: [:average_rating],
      include: { 
        reviews: { only: [:description] } 
      }
    )
  end  

  def average_rating
    reviews.size > 0 ? rating_sum / reviews.size.to_f : 0.0
  end

  private
  
  def rating_sum
    reviews.inject(0) { |sum, review| sum + review.rating }
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminsController

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = "Video created."
      redirect_to new_admin_video_path
    else
      flash[:errors] = "There is a problem with your inputs."
      render :new
    end
  end

  private

  def video_params
    params.require(:video).permit!
  end 
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :require_user

  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
    @review = Review.new
    @reviews = @video.reviews
  end

  def search
    @results = Video.search_by_title(params[:search_term])
  end

  def advanced_search
    options = {
      rating_from: params[:rating_from],
      rating_to: params[:rating_to],
      reviews: params[:search_reviews_enable] == 'y'
    }

    if params[:query]
      @videos = Video.search(params[:query], options).records.to_a
    else
      @videos = []
    end
  end

end

app/views/videos/_video.html.haml
.video.col-sm-2
  = link_to video_path(video), nil do
    %img{ src: video.small_cover, data: { id: video.id } }

app/views/videos/advanced_search.html.haml
%section.advanced_search.container
  = form_tag advanced_search_videos_path, method: :get, class: "form-horizontal" do
    %header
      %h1 Advanced Search
    .form-group
      .col-sm-6
        = search_field_tag :query, params[:query], placeholder: "Search videos by title, description.", class: "form-control"
    .form-group
      .col-sm-6
        = label_tag "search_reviews_enable", "Include Reviews"
        = check_box_tag("search_reviews_enable", 'y', params[:search_reviews_enable] == 'y', class: "checkbox")
    .form-group
      .row.average_rating_label Average Rating
      = label_tag :rating_from, "From:", class: "col-sm-1 control-label"
      .col-sm-2
        = select_tag  "rating_from", options_for_select((10..50).map { |num| num / 10.0 }, params[:rating_from]), prompt: "-" , class: "form-control"
      = label_tag :rating_to, "To:", class: "col-sm-1 control-label"
      .col-sm-2
        = select_tag "rating_to", options_for_select((10..50).map { |num| num / 10.0 }, params[:rating_to]), prompt: "-" , class: "form-control"    
    .form-group
      .col-sm-6
        = button_tag(type: "submit", class: "btn btn-primary") do
          %span.glyphicon.glyphicon-search
          Search
  %hr
  %h2.results_count Results: #{@videos.count} videos found
  - @videos.each do |video|
    %article.video.row
      .video_data
        %figure.col-sm-2
          %img(src="#{video.small_cover}" alt="video cover")
        .video_body.col-sm-10
          %header
            %h3
              Video
              %em.label.label-highlight= video.title
          %p.video_description
            = video.description
          %hr
          .details
            %span.average_rating Average rating: #{video.average_rating}
            %span.reviews_count #{video.reviews.count} reviews
          - video.reviews.each do |review|
            %footer.video_review
              = review.description

app/views/videos/search.html.haml
%article.video_category
  %header
    %h3= "Search Results"
  .videos.row
    - @results.each do |result|
      = render partial: '/videos/video', locals: {video: result}

app/views/videos/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@video.large_cover_url}")
      .video_info.col-sm-3
        %header
          %h3 #{@video.title}
          %span Rating: #{@video.average_rating}/5
        %p #{@video.description}
        .actions
          %a.btn.btn-primary(href="#{@video.video_url}") Watch Now
          - unless current_user.in_queue?(@video)
            = link_to "+ My Queue", queue_items_path(video_id: @video.id), method: "post", class: "btn btn-default"
  %section.reviews.container
    .row
      .col-sm-10.col-sm-offset-1
        = bootstrap_form_for @review, url: video_reviews_path(@video) do |f|
          %fieldset
            .form-group
              %label Rate this video
              .row
                .col-sm-3
                  = f.select :rating, options_for_video_reviews
            .form-group
              %label Write Review
              .row
                .col-sm-8
                  = f.text_area :description, rows: 6, class: "span6"
          %fieldset.form-group.actions.clearfix
            %input(type="submit" value="Submit" class="btn")
            = link_to "Cancel", @video
        %header
          %h3 User Reviews (#{@reviews.size})
        %ul
          - @reviews.each do |review|
            %article.review
              %li.row
                .col-sm-2
                  %span Rating: #{review.rating} / 5
                  %p 
                    by 
                    = link_to review.user.username, user_path(review.user)
                .col-sm-8
                  %p #{review.description}