config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#splash'

  get 'ui(/:action)', controller: 'ui' unless Rails.env.production?

  ### Categories ###
  get '/home', to: 'categories#index'
  get '/genre/:id', to: 'categories#show', as: "category"

  ### Videos > Reviews ###
  resources :videos, only: [:show] do 
    collection do 
      post :search, to: "videos#search"
      get :advanced_search, to: "videos#advanced_search", as: :advanced_search
    end

    resources :reviews, only: [:create]
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  ### Queue ###
  get '/my_queue', to: 'queue_items#index'
  patch '/update_queue', to: 'queue_items#update_queue'
  resources :queue_items, only: [:create, :destroy]

  ### Sessions ###
  get '/login', to: 'sessions#new'
  post '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:create]

  ### Users ###
  get '/register', to: 'users#new'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'
  resources :users, only: [:create, :show]

  ### Followers/Leaders ###
  get '/people', to: 'relationships#index'
  resources :relationships, only: [:destroy, :create]

  ### Forgot Password Workflow ###
  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :forgot_passwords, only: [:create]

  ### Password Reset Workflow ###
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'

  ### Invitations Workflow ###
  resources :invitations, only: [:new, :create]

  mount StripeEvent::Engine => '/stripe_events'
end

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "MyFLiX"
  - if current_user
    %ul.col-md-4.clearfix
      %li= link_to "Videos", home_path
      %li= link_to "My Queue", my_queue_path
      %li= link_to "People", people_path
      %li= link_to "Advanced Search", advanced_search_videos_path
    = form_tag search_videos_path, method: "get", class: "col-md-5 navbar-form" do 
      = text_field_tag "search_term", nil, placeholder: "Search..."
      = submit_tag "Submit"
    #user_links.pull-right
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            Welcome, #{current_user.username}
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li
              = link_to "Invite Friends", new_invitation_path
              = link_to "Account"
              = link_to "Plan and Billing"
              = link_to "Sign Out", logout_path, method: :post 

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - name == 'errors' ? name = 'danger' : name = 'success'
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)